"""Add updated_at field to Post

Revision ID: 430818d96b39
Revises: 5638a8fa2f59
Create Date: 2024-09-25 01:13:23.511419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430818d96b39'
down_revision = '5638a8fa2f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
