version: '3'
services:
  web:
    build: .
    command: gunicorn -c gunicorn_config.py wsgi:app
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
      - rabbitmq
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
    ports:
      - "3308:3306"

  redis:
    image: redis:latest
    ports:
      - "6390:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - web
      - rabbitmq
      - redis
